{
  parserClass="com.apophenic.csharpplugin.parser.CSharpParser"
  parserUtilClass="com.apophenic.csharpplugin.parser.CSharpParserUtil"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="CSharp"
  psiImplClassSuffix="Impl"
  psiPackage="com.apophenic.csharpplugin.psi"
  psiImplPackage="com.apophenic.csharpplugin.psi.impl"

  elementTypeHolderClass="com.apophenic.csharpplugin.psi.CSharpTypes"
  elementTypeClass="com.apophenic.csharpplugin.CSharpElementType"
  tokenTypeClass="com.apophenic.csharpplugin.CSharpTokenType"

  psiImplUtilClass="com.apophenic.csharpplugin.psi.impl.CSharpPropertyImpl"
  generateTokenAccessors=true

  tokens=[
      LBRACE               =  '{'
      RBRACE               =  '}'
      LBRACK               =  '['
      RBRACK               =  ']'
      LPAREN               =  '('
      RPAREN               =  ')'
      COLON                =  ':'
      SEMI                 =  ';'
      COMMA                =  ','
      EQ                   =  '=='
      ASSIGN               =  '='
      NOT_EQ               =  '!='
      NOT                  =  '!'
      PLUS_PLUS            =  '++'
      PLUS_ASSIGN          =  '+='
      PLUS                 =  '+'
      MINUS_MINUS          =  '--'
      MINUS_ASSIGN         =  '-='
      MINUS                =  '-'
      COND_OR              =  '||'
      BIT_OR_ASSIGN        =  '|='
      BIT_CLEAR_ASSIGN     =  '&^='
      BIT_CLEAR            =  '&^'
      COND_AND             =  '&&'
      BIT_AND_ASSIGN       =  '&='
      BIT_AND              =  '&'
      BIT_OR               =  '|'
      SHIFT_LEFT_ASSIGN    =  '<<='
      SHIFT_LEFT           =  '<<'
      LESS_OR_EQUAL        =  '<='
      LESS                 =  '<'
      BIT_XOR_ASSIGN       =  '^='
      BIT_XOR              =  '^'
      MUL_ASSIGN           =  '*='
      MUL                  =  '*'
      QUOTIENT_ASSIGN      =  '/='
      QUOTIENT             =  '/'
      REMAINDER_ASSIGN     =  '%='
      REMAINDER            =  '%'
      SHIFT_RIGHT_ASSIGN   =  '>>='
      SHIFT_RIGHT          =  '>>'
      GREATER_OR_EQUAL     =  '>='
      GREATER              =  '>'
      DOT                  =  '.'
      APOS                 =  ''''
      QUOTE                =  '"'
      BACK                 =  '\'

      WS                   = 'regexp:\s+'
      COMMENT              = 'regexp://.*'
      DIGIT                = 'regexp:\d+(\.\d*)?'
      STRING               = "regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")"
      ID                   = 'regexp:\p{Alpha}\w*'
    ]
}

File ::= ImportList NamespaceDec
ImportList ::= ImportDec*
ImportDec ::= using ID (ID | DOT)* SEMI
NamespaceDec ::= namespace ID LBRACE ClassList RBRACE
ClassList ::= ClassDec*
ClassDec ::= (AccessModifier? ReferenceTypes ID LBRACE MethodList RBRACE)

MethodList ::= (MethodDec | EnumDec | VarDec)*
MethodDec ::= AccessModifier? TypeModifier* Return_type ID LPAREN(Types ID)* RPAREN LBRACE Expr* RBRACE
{pin=8}
EnumDec ::= AccessModifier? enum ID LBRACE (ID ',')* ID* RBRACE

Expr ::= (VarDec)

VarDec ::= AccessModifier? TypeModifier? (BoolDec | ByteDec | CharDec | FloatDec | IntDec | LongDec | ShortDec |
                                          StringDec | ObjectDec | CustomObjectDec)

BoolDec ::= bool ID ASSIGN (true | false) SEMI
ByteDec ::= byte ID ASSIGN (0x DIGIT+)  SEMI // todo
CharDec ::= char ID ASSIGN APOS ([a-zA-Z0-9] | (BACK ('u' | 'x') DIGIT{4})) APOS SEMI
FloatDec ::= float ID ASSIGN DIGIT '.'* 'f' SEMI
IntDec ::= u?int ID ASSIGN DIGIT SEMI
LongDec ::= u?long ID ASSIGN DIGIT SEMI
ShortDec ::= u?short ID ASSIGN DIGIT SEMI
StringDec ::= string ID ASSIGN STRING SEMI
ObjectDec ::= object ID ASSIGN new object LPAREN (ID | DIGIT | STRING) RPAREN SEMI
CustomObjectDec ::= CustomObject ID ASSIGN new CustomObject LPAREN (ID | DIGIT | STRING) RPAREN SEMI

Parameter ::= ID LPAREN ((ValueTypes | ID) ID ','*)* RPAREN



AccessModifier ::= (public | private | protected | internal)
TypeModifier ::= (abstract | async | const | event | extern | new | override | partial | readonly | sealed |
                  static | unsafe | virtual | volatile) // todo split into method modifiers w/ rules

Types ::= (bool | byte | sbyte | char | decimal | double | float | int | uint | long | ulong | object | short |
           ushort | 'string') Array?    // todo
ValueTypes ::= (struct | enum)
ReferenceTypes ::= (class | interface | delegate)

ReservedWords ::= (as | base | break | case | catch | continue | do | else | false | finally | for | foreach | goto |
                   if | in | is | lock | namespace | new | null | out | ref | return | sizeof | stackalloc | switch |
                   this | throw | true | try | typeof | using | while | var | yield)

private Return_type ::= (void | Types | CustomObject)
private CustomObject ::= ID Array?
private Array ::= (LBRACK RBRACK)


